### ISSUE TITLE
License一直失败，重新安装软件+重新申请License，还是一直失败

### ISSUE THREAD

**Issue by mycodingway** [pFindStudio/pFind3#1]
![default](https://user-images.githubusercontent.com/29234643/41597905-5748f2b8-7401-11e8-936d-f78db85b6ef6.PNG)

**把license复制到pFind安装目录下的bin文件夹下后，打开pFIND，出现上图。**
**按照要求Reinstall后还是不行“”

好像是我更新了win10之后出现的？（更新安全补丁之类的，非360，win10系统本身的更新，win10本身版本没变）

**Comment by Hao-Chi** [comment]
@mycodingway Hi, we have fixed the bug and the new version 3.1.3 is released now. please try to use the new version. Thank you.
