### ISSUE TITLE
option of MS instrument

### ISSUE THREAD

**Issue by chenxihuang** [pFindStudio/pFind3#11]
Dear pFind Team,

For the MS instrument option, my instrument is (ESI) LTQ Orbitrap XL, vendor: Thermo.
Fragmentation Mode: CID, CAD(y and b ions)
MS Scan Mode:FT-ICR/Orbitrap
MS/MS Scan Mode: Linear Ion Trap 

I was wondering if **CID-FTMS** is the correct option for me?

Regards
Chenxi

**Comment by Hao-Chi** [comment]
黄老师，您好！我看了您的输出日志，似乎应该是CID-ITMS。您可以先试试。谢谢！
