### ISSUE TITLE
Invalid_msmspath1_Path

### ISSUE THREAD

**Issue by chenxihuang** [pFindStudio/pFind3#12]
pFind team，您好，

我尝试了两个我的.raw data，按照user guide运行了pFind，都跳出同样的弹窗：pFindTask2/3 has been stopped!
我用的仪器是Thermo的(ESI) LTQ Orbitrap XL
我的设置选项和running log附件可见

祝好 
黄辰曦

[summary.pdf](https://github.com/pFindStudio/pFind3/files/2534325/summary.pdf)
[running_log_2018-10-31.log](https://github.com/pFindStudio/pFind3/files/2534315/running_log_2018-10-31.log)

**Comment by chenxihuang** [comment]
然后我尝试了一下先把raw data用MScovert转成mgf data，pFind似乎可以继续进行，但是结束的时候会跳出另一个弹窗，而且尝试用pBuild打开task的时候也跳出同样如图弹窗：
[running_log_2018-10-31-2.log](https://github.com/pFindStudio/pFind3/files/2534501/running_log_2018-10-31-2.log)

![image](https://user-images.githubusercontent.com/12170447/47790742-3d2b4680-dd18-11e8-928b-ff823c8976f9.png)

**Comment by Hao-Chi** [comment]
黄老师，您好，您可以把参数配置第一页对应的质谱碎裂类型修改为CID-ITMS，应该就可以了。谢谢您！
