### ISSUE TITLE
Spectral library

### ISSUE THREAD

**Issue by jhdavislab** [pFindStudio/pFind3#17]
Very impressive tool! We are interested in using it to generate spectral libraries for downstream processing of datasets in Skyline - is there currently a way to export the library of PSMs such that they can be read by Skyline (or a plan to implement the ability to export a .pep.xml file)?

Thanks again!
joey

**Comment by xuesu** [comment]
honestly I am currently doing an similiar job by generating a tsv file.
honestly it is too boring that i haven't updated for a half year.
but please send an email to pfind@ict.ac.cn or xuxinyi@ict.ac.cn and then we can discuss about it. skyline is really impressive.
