### ISSUE TITLE
Invalid_msmspath1_Path

### ISSUE THREAD

**Issue by pklundquist** [pFindStudio/pFind3#18]
I am new to pFind and am trying to do an open search of a single Q-Exactive RAW file. I have not been able to complete the analysis as I get the following error message:

[pFind] ALERT: Invalid_msmspath1_Path: [C:\Program Files\pFindStudio\pFind3\Data Repository\QX00870_CIDIT.pf2]

I have attached the full report to this posting.

I appreciate any advice on how to get around this. Am I setting up the analysis incorrectly or is this a bug?

Thanks!

[running_log_2018-12-10.log](https://github.com/pFindStudio/pFind3/files/2664380/running_log_2018-12-10.log)

**Comment by KunathBJ** [comment]
Hey everybody.
Did anybody got a solution for that issue? I'm having the same problem and I can't figure out what I've done wrong.

Thanks a lot,

Ben

**Comment by jfguo01** [comment]
I find your data path:\Program Files\pFindStudio\pFind3\Data Repository\QX00870.raw exist space character, maybe you can change your data path without blank character and try it again.

**Comment by KunathBJ** [comment]
Hey.
Actually in my case I don't have any space in my path.
Here is my log file:
[running_log_2019-01-25.txt](https://github.com/pFindStudio/pFind3/files/2802185/running_log_2019-01-25.txt)

**Comment by KunathBJ** [comment]
Hey guys!
Do you have any idea?

**Comment by yuzhuxuyang** [comment]
I have the same issue. After testing for several times, I found if we used CID-ITMS or CID-FTMS, then we will meet this question.
Could you tell us how to figure it out?
Much appreciate!

**Comment by yuzhuxuyang** [comment]
I used this raw file:
https://www.ebi.ac.uk/pride/data/archive/2014/05/PXD000865/00645_E02_P004893_B0M_A00_R1.raw
And if I used CID-FTMS or CID-ITMS, it would stop and output error.
Could you check why does it happen?
Thanks so much.

**Comment by xuesu** [comment]
@nelson42 that's because pparse and pfind runs seperately. When pparse tries to output potential precursors, it does not know your instrument settings in pfind and has to guess it. HCDFT means pparse will refine the precursor infos and others means pparse will do nothing. That's why they are different. pls use the one showed after using pparse instead of your former settings.

**Comment by khal3dj** [comment]
Hi all, this question issue has been posted three times without an actual resolution. Will the developers please investigate? 
Thank you for creating this tool
