### ISSUE TITLE
errors in pFind

### ISSUE THREAD

**Issue by jfguo01** [pFindStudio/pFind3#24]
Hi, Hao-Chi.

I met some problems when I used the pFind serach my N15 labeling data, there show nothing in the pBuild. I send the E-mail to your address, but I hadn't received the reply. Could you help me dissovle this problem? Additionally, do you have a precised protocol that introduce how to use the pFind serach, like the parameters setting etc. Thanks.

**Comment by Hao-Chi** [comment]
Hi @jfguo01 , 

I have sent you an e-mail a few days ago. If you have any questions please do not hesitate to contact me.

Best.

Hao
