### ISSUE TITLE
How to open the result files like .summary or .spectra files sended by others?

### ISSUE THREAD

**Issue by 1996yingyingying** [pFindStudio/pFind3#27]
Hi, I got the pfind search result files in .summary and .spectra format sended by others, how can I open these files and view the results? Thanks a lot!

**Comment by 01joy** [comment]
Dear @1996yingyingying ,

You can open pFind results with any editor such as [NotePad++](https://notepad-plus-plus.org/), or you can just drag the file and drop it into Excel. The .spectra file is splitted by tab.

**Comment by 1996yingyingying** [comment]
Ok, thank you!

**Comment by 1996yingyingying** [comment]
I opened them by excel, thank you! 17210220018 邮箱17210220018@fudan.edu.cn 签名由 网易邮箱大师 定制 On 02/16/2019 22:36, bitJoy wrote: Dear @1996yingyingying , You can open pFind results with any editor such as NotePad++, or you can just drag the file and drop it into Excel. The .spectra file is splitted by tab. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
