### ISSUE TITLE
Email to pfind@ict.ac.cn is being rejected

### ISSUE THREAD

**Issue by zrolfs** [pFindStudio/pFind3#36]
Hi,
I'd like to get a license to use pFind3, but I can't seem to get through via e-mail.

Application date: 2019.08.14
User name: Zachary Rolfs
University / Company: University of Wisconsin-Madison
Work email address: zrolfs@wisc.edu
Lab leader / Supervisor: Lloyd Smith
Supervisor's email: smith@chem.wisc.edu
Country / Region: United States
How do you hear about pFind: Open-pFind enables precise, comprehensive and rapid peptide identification in shotgun proteomics
What can pFind do for you: Identify novel PTMs
Activation code: 35C7A3F1E5F987623F10DB0D965D03B5

Thanks,
Zach

**Comment by xuesu** [comment]
i have sent it.
