### ISSUE TITLE
pFIND的重大bug：鉴定到了海量的不存在的电荷肽的肽段

### ISSUE THREAD

**Issue by mycodingway** [pFindStudio/pFind3#4]
pFIND调用的电荷识别算法存在重大问题：

**样品质谱方法：**    BS3交联，排除1+ 2+；
**正确情况**：用MSconvert将上述Raw转换成MGF后，没有发现任何2+ 的二级谱图，与理论情况相同，因为质谱仪上已经将2+的母离子排除，不打二级。
 
![1](https://user-images.githubusercontent.com/29234643/45274763-7bac3e00-b4eb-11e8-8293-493db51a8bf9.png)

**pFIND情况：**   用pFIND搜完之后的结果文件夹里的mgf文件打开后，发现有1万多个2+的二级谱图。
如下图所示：（pFIND搜完库之后在结果文件夹中的mgf的二电荷计数）
 
![2](https://user-images.githubusercontent.com/29234643/45274787-91b9fe80-b4eb-11e8-9d03-d0e8a788cda1.png)
![3](https://user-images.githubusercontent.com/29234643/45274790-967eb280-b4eb-11e8-84cf-0a1a30adc11c.png)

**这个问题请问怎么解决呢？还是我有所误解？**

**Comment by xuesu** [comment]
这是因为您所看的是预处理步骤，输出潜在的母离子，而预处理软件的设置是找不到母离子电荷就默认为2
