### ISSUE TITLE
Small typos and problem with admin privileges

### ISSUE THREAD

**Issue by AndreLuettig** [pFindStudio/pFind3#5]
Hey, 
first of all, great work!

I've just seen two typos in the peptide tab in the Results view, where there is Detla instead of Delta in two columns:
![grafik](https://user-images.githubusercontent.com/43988390/46662112-db653a00-cbba-11e8-846c-478ddb818471.png)

Furthermore I have a problem with using the program at my lab, since we all have a general administrator for the computers (where we know the password and stuff), but since the program requires admin at start, it copies the txt Results made from "Export to TXT" in the result view to the admin accounts folder and I cannot move them from within the program to a different location with the following error:

![grafik](https://user-images.githubusercontent.com/43988390/46662316-5f1f2680-cbbb-11e8-93de-5fd2f2840846.png)

(Sorry for german spam, roughly it means [Path] is not accessible. Access denied.)

Maybe you can make it, so the program itself does not need administrator privileges to run, but only the installer?

Best regards,
André

**Comment by AndreLuettig** [comment]
Please ignore the last bit with the denied path, I just didn't set up the path correctly. If I'm choosing the path to my local user directory in the setup, it works!

**Comment by Hao-Chi** [comment]
Hi,

Thank you very much for your comment and sorry for the late reply. We will fix the typos in the next version of pFind.

**Comment by radusuciu** [comment]
Any chance of removing requirement to run with admin privileges? This is a bit of a roadblock.
